version: '3'

silent: true

includes:
  doc:
    taskfile: doc
    dir: doc

vars:
  PRINT_BEGIN: '\033[32m\xE2\x9c\x93'
  PRINT_END: '\n\n\033[0m'

tasks:
  generate_docs:
    desc: generate APIs documentation in doc/dist
    cmds:
      - printf "{{.PRINT_BEGIN}} Generate Documentation {{.PRINT_END}}"
      - task doc:lint
      - task doc:build
